import React from 'react';

import { Select } from 'semantic-ui-react';

const countries = [
    { text: 'Aruba', value: 'AW' },
    { text: 'Afghanistan', value: 'AF' },
    { text: 'Angola', value: 'AO' },
    { text: 'Anguilla', value: 'AI' },
    { text: 'Åland Islands', value: 'AX' },
    { text: 'Albania', value: 'AL' },
    { text: 'Andorra', value: 'AD' },
    { text: 'United Arab Emirates', value: 'AE' },
    { text: 'Argentina', value: 'AR' },
    { text: 'Armenia', value: 'AM' },
    { text: 'American Samoa', value: 'AS' },
    { text: 'Antarctica', value: 'AQ' },
    { text: 'French Southern and Antarctic Lands', value: 'TF' },
    { text: 'Antigua and Barbuda', value: 'AG' },
    { text: 'Australia', value: 'AU' },
    { text: 'Austria', value: 'AT' },
    { text: 'Azerbaijan', value: 'AZ' },
    { text: 'Burundi', value: 'BI' },
    { text: 'Belgium', value: 'BE' },
    { text: 'Benin', value: 'BJ' },
    { text: 'Burkina Faso', value: 'BF' },
    { text: 'Bangladesh', value: 'BD' },
    { text: 'Bulgaria', value: 'BG' },
    { text: 'Bahrain', value: 'BH' },
    { text: 'Bahamas', value: 'BS' },
    { text: 'Bosnia and Herzegovina', value: 'BA' },
    { text: 'Saint Barthélemy', value: 'BL' },
    { text: 'Belarus', value: 'BY' },
    { text: 'Belize', value: 'BZ' },
    { text: 'Bermuda', value: 'BM' },
    { text: 'Bolivia', value: 'BO' },
    { text: 'Brazil', value: 'BR' },
    { text: 'Barbados', value: 'BB' },
    { text: 'Brunei', value: 'BN' },
    { text: 'Bhutan', value: 'BT' },
    { text: 'Bouvet Island', value: 'BV' },
    { text: 'Botswana', value: 'BW' },
    { text: 'Central African Republic', value: 'CF' },
    { text: 'Canada', value: 'CA' },
    { text: 'Cocos (Keeling) Islands', value: 'CC' },
    { text: 'Switzerland', value: 'CH' },
    { text: 'Chile', value: 'CL' },
    { text: 'China', value: 'CN' },
    { text: 'Ivory Coast', value: 'CI' },
    { text: 'Cameroon', value: 'CM' },
    { text: 'DR Congo', value: 'CD' },
    { text: 'Republic of the Congo', value: 'CG' },
    { text: 'Cook Islands', value: 'CK' },
    { text: 'Colombia', value: 'CO' },
    { text: 'Comoros', value: 'KM' },
    { text: 'Cape Verde', value: 'CV' },
    { text: 'Costa Rica', value: 'CR' },
    { text: 'Cuba', value: 'CU' },
    { text: 'Curaçao', value: 'CW' },
    { text: 'Christmas Island', value: 'CX' },
    { text: 'Cayman Islands', value: 'KY' },
    { text: 'Cyprus', value: 'CY' },
    { text: 'Czech Republic', value: 'CZ' },
    { text: 'Germany', value: 'DE' },
    { text: 'Djibouti', value: 'DJ' },
    { text: 'Dominica', value: 'DM' },
    { text: 'Denmark', value: 'DK' },
    { text: 'Dominican Republic', value: 'DO' },
    { text: 'Algeria', value: 'DZ' },
    { text: 'Ecuador', value: 'EC' },
    { text: 'Egypt', value: 'EG' },
    { text: 'Eritrea', value: 'ER' },
    { text: 'Western Sahara', value: 'EH' },
    { text: 'Spain', value: 'ES' },
    { text: 'Estonia', value: 'EE' },
    { text: 'Ethiopia', value: 'ET' },
    { text: 'Finland', value: 'FI' },
    { text: 'Fiji', value: 'FJ' },
    { text: 'Falkland Islands', value: 'FK' },
    { text: 'France', value: 'FR' },
    { text: 'Faroe Islands', value: 'FO' },
    { text: 'Micronesia', value: 'FM' },
    { text: 'Gabon', value: 'GA' },
    { text: 'United Kingdom', value: 'GB' },
    { text: 'Georgia', value: 'GE' },
    { text: 'Guernsey', value: 'GG' },
    { text: 'Ghana', value: 'GH' },
    { text: 'Gibraltar', value: 'GI' },
    { text: 'Guinea', value: 'GN' },
    { text: 'Guadeloupe', value: 'GP' },
    { text: 'Gambia', value: 'GM' },
    { text: 'Guinea-Bissau', value: 'GW' },
    { text: 'Equatorial Guinea', value: 'GQ' },
    { text: 'Greece', value: 'GR' },
    { text: 'Grenada', value: 'GD' },
    { text: 'Greenland', value: 'GL' },
    { text: 'Guatemala', value: 'GT' },
    { text: 'French Guiana', value: 'GF' },
    { text: 'Guam', value: 'GU' },
    { text: 'Guyana', value: 'GY' },
    { text: 'Hong Kong', value: 'HK' },
    { text: 'Heard Island and McDonald Islands', value: 'HM' },
    { text: 'Honduras', value: 'HN' },
    { text: 'Croatia', value: 'HR' },
    { text: 'Haiti', value: 'HT' },
    { text: 'Hungary', value: 'HU' },
    { text: 'Indonesia', value: 'ID' },
    { text: 'Isle of Man', value: 'IM' },
    { text: 'India', value: 'IN' },
    { text: 'British Indian Ocean Territory', value: 'IO' },
    { text: 'Ireland', value: 'IE' },
    { text: 'Iran', value: 'IR' },
    { text: 'Iraq', value: 'IQ' },
    { text: 'Iceland', value: 'IS' },
    { text: 'Israel', value: 'IL' },
    { text: 'Italy', value: 'IT' },
    { text: 'Jamaica', value: 'JM' },
    { text: 'Jersey', value: 'JE' },
    { text: 'Jordan', value: 'JO' },
    { text: 'Japan', value: 'JP' },
    { text: 'Kazakhstan', value: 'KZ' },
    { text: 'Kenya', value: 'KE' },
    { text: 'Kyrgyzstan', value: 'KG' },
    { text: 'Cambodia', value: 'KH' },
    { text: 'Kiribati', value: 'KI' },
    { text: 'Saint Kitts and Nevis', value: 'KN' },
    { text: 'South Korea', value: 'KR' },
    { text: 'Kosovo', value: 'XK' },
    { text: 'Kuwait', value: 'KW' },
    { text: 'Laos', value: 'LA' },
    { text: 'Lebanon', value: 'LB' },
    { text: 'Liberia', value: 'LR' },
    { text: 'Libya', value: 'LY' },
    { text: 'Saint Lucia', value: 'LC' },
    { text: 'Liechtenstein', value: 'LI' },
    { text: 'Sri Lanka', value: 'LK' },
    { text: 'Lesotho', value: 'LS' },
    { text: 'Lithuania', value: 'LT' },
    { text: 'Luxembourg', value: 'LU' },
    { text: 'Latvia', value: 'LV' },
    { text: 'Macau', value: 'MO' },
    { text: 'Saint Martin', value: 'MF' },
    { text: 'Morocco', value: 'MA' },
    { text: 'Monaco', value: 'MC' },
    { text: 'Moldova', value: 'MD' },
    { text: 'Madagascar', value: 'MG' },
    { text: 'Maldives', value: 'MV' },
    { text: 'Mexico', value: 'MX' },
    { text: 'Marshall Islands', value: 'MH' },
    { text: 'Macedonia', value: 'MK' },
    { text: 'Mali', value: 'ML' },
    { text: 'Malta', value: 'MT' },
    { text: 'Myanmar', value: 'MM' },
    { text: 'Montenegro', value: 'ME' },
    { text: 'Mongolia', value: 'MN' },
    { text: 'Northern Mariana Islands', value: 'MP' },
    { text: 'Mozambique', value: 'MZ' },
    { text: 'Mauritania', value: 'MR' },
    { text: 'Montserrat', value: 'MS' },
    { text: 'Martinique', value: 'MQ' },
    { text: 'Mauritius', value: 'MU' },
    { text: 'Malawi', value: 'MW' },
    { text: 'Malaysia', value: 'MY' },
    { text: 'Mayotte', value: 'YT' },
    { text: 'Namibia', value: 'NA' },
    { text: 'New Caledonia', value: 'NC' },
    { text: 'Niger', value: 'NE' },
    { text: 'Norfolk Island', value: 'NF' },
    { text: 'Nigeria', value: 'NG' },
    { text: 'Nicaragua', value: 'NI' },
    { text: 'Niue', value: 'NU' },
    { text: 'Netherlands', value: 'NL' },
    { text: 'Norway', value: 'NO' },
    { text: 'Nepal', value: 'NP' },
    { text: 'Nauru', value: 'NR' },
    { text: 'New Zealand', value: 'NZ' },
    { text: 'Oman', value: 'OM' },
    { text: 'Pakistan', value: 'PK' },
    { text: 'Panama', value: 'PA' },
    { text: 'Pitcairn Islands', value: 'PN' },
    { text: 'Peru', value: 'PE' },
    { text: 'Philippines', value: 'PH' },
    { text: 'Palau', value: 'PW' },
    { text: 'Papua New Guinea', value: 'PG' },
    { text: 'Poland', value: 'PL' },
    { text: 'Puerto Rico', value: 'PR' },
    { text: 'North Korea', value: 'KP' },
    { text: 'Portugal', value: 'PT' },
    { text: 'Paraguay', value: 'PY' },
    { text: 'Palestine', value: 'PS' },
    { text: 'French Polynesia', value: 'PF' },
    { text: 'Qatar', value: 'QA' },
    { text: 'Réunion', value: 'RE' },
    { text: 'Romania', value: 'RO' },
    { text: 'Russia', value: 'RU' },
    { text: 'Rwanda', value: 'RW' },
    { text: 'Saudi Arabia', value: 'SA' },
    { text: 'Sudan', value: 'SD' },
    { text: 'Senegal', value: 'SN' },
    { text: 'Singapore', value: 'SG' },
    { text: 'South Georgia', value: 'GS' },
    { text: 'Svalbard and Jan Mayen', value: 'SJ' },
    { text: 'Solomon Islands', value: 'SB' },
    { text: 'Sierra Leone', value: 'SL' },
    { text: 'El Salvador', value: 'SV' },
    { text: 'San Marino', value: 'SM' },
    { text: 'Somalia', value: 'SO' },
    { text: 'Saint Pierre and Miquelon', value: 'PM' },
    { text: 'Serbia', value: 'RS' },
    { text: 'South Sudan', value: 'SS' },
    { text: 'São Tomé and Príncipe', value: 'ST' },
    { text: 'Suriname', value: 'SR' },
    { text: 'Slovakia', value: 'SK' },
    { text: 'Slovenia', value: 'SI' },
    { text: 'Sweden', value: 'SE' },
    { text: 'Swaziland', value: 'SZ' },
    { text: 'Sint Maarten', value: 'SX' },
    { text: 'Seychelles', value: 'SC' },
    { text: 'Syria', value: 'SY' },
    { text: 'Turks and Caicos Islands', value: 'TC' },
    { text: 'Chad', value: 'TD' },
    { text: 'Togo', value: 'TG' },
    { text: 'Thailand', value: 'TH' },
    { text: 'Tajikistan', value: 'TJ' },
    { text: 'Tokelau', value: 'TK' },
    { text: 'Turkmenistan', value: 'TM' },
    { text: 'Timor-Leste', value: 'TL' },
    { text: 'Tonga', value: 'TO' },
    { text: 'Trinidad and Tobago', value: 'TT' },
    { text: 'Tunisia', value: 'TN' },
    { text: 'Turkey', value: 'TR' },
    { text: 'Tuvalu', value: 'TV' },
    { text: 'Taiwan', value: 'TW' },
    { text: 'Tanzania', value: 'TZ' },
    { text: 'Uganda', value: 'UG' },
    { text: 'Ukraine', value: 'UA' },
    { text: 'United States Minor Outlying Islands', value: 'UM' },
    { text: 'Uruguay', value: 'UY' },
    { text: 'United States', value: 'US' },
    { text: 'Uzbekistan', value: 'UZ' },
    { text: 'Vatican City', value: 'VA' },
    { text: 'Saint Vincent and the Grenadines', value: 'VC' },
    { text: 'Venezuela', value: 'VE' },
    { text: 'British Virgin Islands', value: 'VG' },
    { text: 'United States Virgin Islands', value: 'VI' },
    { text: 'Vietnam', value: 'VN' },
    { text: 'Vanuatu', value: 'VU' },
    { text: 'Wallis and Futuna', value: 'WF' },
    { text: 'Samoa', value: 'WS' },
    { text: 'Yemen', value: 'YE' },
    { text: 'South Africa', value: 'ZA' },
    { text: 'Zambia', value: 'ZM' },
    { text: 'Zimbabwe', value: 'ZW' },
];

export default function({ ...props }) {
    return React.createElement(Select, {
        ...props,
        options: countries,
    });
}
