// flow-typed signature: 1fc7675e884ecebd4d91c383f76397bb
// flow-typed version: <<STUB>>/uikit_vgit+ssh://git@gitlab.com/bookly/UIKit.git/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uikit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uikit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uikit/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'uikit/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'uikit/dist/index' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/@kadira/react-storybook-decorator-centered_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/@kadira/storybook_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/css-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/empty_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/es6-promise-debounce_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-config-react-app_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/jest_v17.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/jquery_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/radium_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/react-portal_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/react-select_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/semantic-ui-calendar_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/semantic-ui-css_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/style-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/AirportSelect' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Avatar.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Breadcrumb.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Button.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Checkbox.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Counter.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Divider.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Header.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Icon.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Input.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Loader.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Menu.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Message.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Search.spec' {
  declare module.exports: any;
}

declare module 'uikit/src/components/__tests__/Tab' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Avatar' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Calendar' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Checkbox' {
  declare module.exports: any;
}

declare module 'uikit/src/components/CheckboxList' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Counter' {
  declare module.exports: any;
}

declare module 'uikit/src/components/EllipsisLoader' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Form' {
  declare module.exports: any;
}

declare module 'uikit/src/components/index' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Link' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Slider' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Avatar' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Calendar' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Checkbox' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/CheckboxList' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Counter' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/EllipsisLoader' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/fixtures' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Slider' {
  declare module.exports: any;
}

declare module 'uikit/src/components/stories/Tab' {
  declare module.exports: any;
}

declare module 'uikit/src/components/styles' {
  declare module.exports: any;
}

declare module 'uikit/src/components/Tab' {
  declare module.exports: any;
}

declare module 'uikit/src/index' {
  declare module.exports: any;
}

declare module 'uikit/src/intl/config' {
  declare module.exports: any;
}

declare module 'uikit/src/intl/locales/index' {
  declare module.exports: any;
}

declare module 'uikit/src/lib/jest/intl' {
  declare module.exports: any;
}

declare module 'uikit/src/lib/popupWithCondition' {
  declare module.exports: any;
}

declare module 'uikit/src/types' {
  declare module.exports: any;
}

declare module 'uikit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uikit/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'uikit/coverage/lcov-report/prettify'>;
}
declare module 'uikit/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'uikit/coverage/lcov-report/sorter'>;
}
declare module 'uikit/dist/index.js' {
  declare module.exports: $Exports<'uikit/dist/index'>;
}
declare module 'uikit/flow-typed/npm/@kadira/react-storybook-decorator-centered_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/@kadira/react-storybook-decorator-centered_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/@kadira/storybook_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/@kadira/storybook_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'uikit/flow-typed/npm/css-loader_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/css-loader_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/empty_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/empty_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/es6-promise-debounce_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/es6-promise-debounce_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-config-react-app_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-config-react-app_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-loader_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-loader_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'uikit/flow-typed/npm/jest_v17.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/jest_v17.x.x'>;
}
declare module 'uikit/flow-typed/npm/jquery_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/jquery_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'uikit/flow-typed/npm/radium_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/radium_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/react-portal_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/react-portal_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/react-select_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/react-select_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/semantic-ui-calendar_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/semantic-ui-calendar_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/semantic-ui-css_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/semantic-ui-css_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/style-loader_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/style-loader_vx.x.x'>;
}
declare module 'uikit/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'uikit/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'uikit/src/components/__tests__/AirportSelect.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/AirportSelect'>;
}
declare module 'uikit/src/components/__tests__/Avatar.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Avatar.spec'>;
}
declare module 'uikit/src/components/__tests__/Breadcrumb.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Breadcrumb.spec'>;
}
declare module 'uikit/src/components/__tests__/Button.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Button.spec'>;
}
declare module 'uikit/src/components/__tests__/Checkbox.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Checkbox.spec'>;
}
declare module 'uikit/src/components/__tests__/Counter.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Counter.spec'>;
}
declare module 'uikit/src/components/__tests__/Divider.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Divider.spec'>;
}
declare module 'uikit/src/components/__tests__/Header.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Header.spec'>;
}
declare module 'uikit/src/components/__tests__/Icon.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Icon.spec'>;
}
declare module 'uikit/src/components/__tests__/Input.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Input.spec'>;
}
declare module 'uikit/src/components/__tests__/Loader.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Loader.spec'>;
}
declare module 'uikit/src/components/__tests__/Menu.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Menu.spec'>;
}
declare module 'uikit/src/components/__tests__/Message.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Message.spec'>;
}
declare module 'uikit/src/components/__tests__/Search.spec.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Search.spec'>;
}
declare module 'uikit/src/components/__tests__/Tab.jsx' {
  declare module.exports: $Exports<'uikit/src/components/__tests__/Tab'>;
}
declare module 'uikit/src/components/Avatar.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Avatar'>;
}
declare module 'uikit/src/components/Calendar.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Calendar'>;
}
declare module 'uikit/src/components/Checkbox.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Checkbox'>;
}
declare module 'uikit/src/components/CheckboxList.jsx' {
  declare module.exports: $Exports<'uikit/src/components/CheckboxList'>;
}
declare module 'uikit/src/components/Counter.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Counter'>;
}
declare module 'uikit/src/components/EllipsisLoader.jsx' {
  declare module.exports: $Exports<'uikit/src/components/EllipsisLoader'>;
}
declare module 'uikit/src/components/Form.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Form'>;
}
declare module 'uikit/src/components/index.js' {
  declare module.exports: $Exports<'uikit/src/components/index'>;
}
declare module 'uikit/src/components/Link.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Link'>;
}
declare module 'uikit/src/components/Slider.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Slider'>;
}
declare module 'uikit/src/components/stories/Avatar.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Avatar'>;
}
declare module 'uikit/src/components/stories/Calendar.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Calendar'>;
}
declare module 'uikit/src/components/stories/Checkbox.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Checkbox'>;
}
declare module 'uikit/src/components/stories/CheckboxList.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/CheckboxList'>;
}
declare module 'uikit/src/components/stories/Counter.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Counter'>;
}
declare module 'uikit/src/components/stories/EllipsisLoader.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/EllipsisLoader'>;
}
declare module 'uikit/src/components/stories/fixtures.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/fixtures'>;
}
declare module 'uikit/src/components/stories/Slider.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Slider'>;
}
declare module 'uikit/src/components/stories/Tab.js' {
  declare module.exports: $Exports<'uikit/src/components/stories/Tab'>;
}
declare module 'uikit/src/components/styles.js' {
  declare module.exports: $Exports<'uikit/src/components/styles'>;
}
declare module 'uikit/src/components/Tab.jsx' {
  declare module.exports: $Exports<'uikit/src/components/Tab'>;
}
declare module 'uikit/src/index.js' {
  declare module.exports: $Exports<'uikit/src/index'>;
}
declare module 'uikit/src/intl/config.js' {
  declare module.exports: $Exports<'uikit/src/intl/config'>;
}
declare module 'uikit/src/intl/locales/index.js' {
  declare module.exports: $Exports<'uikit/src/intl/locales/index'>;
}
declare module 'uikit/src/lib/jest/intl.js' {
  declare module.exports: $Exports<'uikit/src/lib/jest/intl'>;
}
declare module 'uikit/src/lib/popupWithCondition.js' {
  declare module.exports: $Exports<'uikit/src/lib/popupWithCondition'>;
}
declare module 'uikit/src/types.js' {
  declare module.exports: $Exports<'uikit/src/types'>;
}
declare module 'uikit/webpack.config.js' {
  declare module.exports: $Exports<'uikit/webpack.config'>;
}
